// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/notify.proto

package notifypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Ts            string                 `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *Message) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_proto_notify_proto protoreflect.FileDescriptor

const file_proto_notify_proto_rawDesc = "" +
	"\n" +
	"\x12proto/notify.proto\x12\x06notify\"\x0f\n" +
	"\rStreamRequest\"E\n" +
	"\aMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\tR\x02ts\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload2>\n" +
	"\bNotifier\x122\n" +
	"\x06Stream\x12\x15.notify.StreamRequest\x1a\x0f.notify.Message0\x01BGZEgithub.com/y-hashisaka/try-notification-golang/06-grpcstream/notifypbb\x06proto3"

var (
	file_proto_notify_proto_rawDescOnce sync.Once
	file_proto_notify_proto_rawDescData []byte
)

func file_proto_notify_proto_rawDescGZIP() []byte {
	file_proto_notify_proto_rawDescOnce.Do(func() {
		file_proto_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notify_proto_rawDesc), len(file_proto_notify_proto_rawDesc)))
	})
	return file_proto_notify_proto_rawDescData
}

var file_proto_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_notify_proto_goTypes = []any{
	(*StreamRequest)(nil), // 0: notify.StreamRequest
	(*Message)(nil),       // 1: notify.Message
}
var file_proto_notify_proto_depIdxs = []int32{
	0, // 0: notify.Notifier.Stream:input_type -> notify.StreamRequest
	1, // 1: notify.Notifier.Stream:output_type -> notify.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_notify_proto_init() }
func file_proto_notify_proto_init() {
	if File_proto_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notify_proto_rawDesc), len(file_proto_notify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notify_proto_goTypes,
		DependencyIndexes: file_proto_notify_proto_depIdxs,
		MessageInfos:      file_proto_notify_proto_msgTypes,
	}.Build()
	File_proto_notify_proto = out.File
	file_proto_notify_proto_goTypes = nil
	file_proto_notify_proto_depIdxs = nil
}
